forge 'http://forge.puppetlabs.com'

mod 'CERNOps/motd', '0.1.3'
mod 'jfryman/nginx', '0.0.8'
mod 'spantree/java7', '0.2.2'
mod 'hubspot/nexus', :git => 'https://github.com/Spantree/puppet-nexus.git', :ref => '1d50dd59d7d182f6f25e6dbc4bbe8506608d8f8a'
mod 'ghoneycutt/ssh', '3.15.0'
mod 'puppetlabs/stdlib', '4.2.2'
mod 'jdowning/awscli', '0.1.0'
